"""empty message

Revision ID: 7112076d18d2
Revises: da9de256d503
Create Date: 2024-10-24 12:34:53.080603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7112076d18d2'
down_revision = 'da9de256d503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_word_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_word_id'], ['gamewordofday.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_score_api',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_api.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guess_api',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guess_number', sa.Integer(), nullable=False),
    sa.Column('guess_word', sa.String(length=5), nullable=False),
    sa.Column('guess_score', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_api.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guess_api', schema=None) as batch_op:
        batch_op.create_index('idx_apigame_id', ['game_id'], unique=False)
        batch_op.create_index('idx_apigame_id_guess_number', ['game_id', 'guess_number'], unique=False)

    with op.batch_alter_table('game_score', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('guess_api', schema=None) as batch_op:
        batch_op.drop_index('idx_apigame_id_guess_number')
        batch_op.drop_index('idx_apigame_id')

    op.drop_table('guess_api')
    op.drop_table('game_score_api')
    op.drop_table('game_api')
    # ### end Alembic commands ###
