"""Add list of valid Wordle words

Revision ID: e7d0be82888c
Revises: 4575eb2b1558
Create Date: 2024-07-03 14:17:42.265871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d0be82888c'
down_revision = '4575eb2b1558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlewords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordlewords')
    # ### end Alembic commands ###
